package kt.koyakei.nationalBaseRegistry.administrativeLocationRegister.event.store

import kt.koyakei.locationadministrator.aggregate.AdministrativeLocationAggregate

data class LocationPriceCreateSnapShotEvent(val id: String, val administrativeLocationAggregate: AdministrativeLocationAggregate)