package kt.koyakei.nationalBaseRegistry.administrativeLocationRegister.event.store

import kt.koyakei.nationalBaseRegistry.administrativeLocationRegister.aggregate.AdministrativeLocationAggregate


data class LocationPriceCreateSnapShotEvent(val id: String, val administrativeLocationAggregate: AdministrativeLocationAggregate)